### ISSUE TITLE
Send Emails button Releated Issue.

### ISSUE THREAD

**Issue by vishdha** [vishdha/Meeting#2]
In Meeting Child Table Invitation contain Send Emails Button. When I pressed it prompt message "Please setup default Email Account from Setup > Email > Email Account". 

wrote script in meeting.js , meeting.js and api.py.

for reference: I used Frappe Developer Tool Youtube video Session 5: Scripting DocType II
@revant
@gaurav-naik

**Comment by revant** [comment]
https://www.youtube.com/watch?v=YFYe0DrB95o
